name: Daily Auto Commit

on:
  push:
    branches:
      - main
  schedule:
    - cron: '15 17 * * *'
  workflow_dispatch:

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TZ: Asia/Jakarta

    steps:
      - name: DEBUG
        run: echo "::debug::Ref = ${{github.ref}}"

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Modify README.md
        run: |
          d=$(date '+%Y-%m-%d %H:%M:%S')
          
          echo "# Commit at $d" > README.md

      - name: Commit changes
        run: |
          git config --local user.name "ItsMe-RiiK"
          git config --local user.email "syakirr266@gmail.com"
          git add README.md

          d=$(date '+%Y-%m-%d %H:%M:%S')
          git commit -m "Commit at $d" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
